### ISSUE TITLE
How to change to latest manifest when using repo sync?

### ISSUE THREAD

**Issue by perqin** [divis1969/android_device_meizu_meilan2#44]
I am very sorry for asking such a fool question, but I get few help from other place...I have sync v0.4 before but your repo has already been updated to v0.7, so how can I sync the latest version?

**Comment by divis1969** [comment]
Do repo init again for new version and then repo sync:

```
repo init -u git://github.com/divis1969/android.git -b meilan2 -m meilan2-cm-12.1-v0.7.xml
repo sync
```

If repo sync fails with an error, most likely you need to re-sycn this particular repository with `--force-sync` option (just read the error message) and then repo sync again (there could be several such errors). Perhaps you can use `--force-sync` for all the repos, I just did not try this.

**Comment by divis1969** [comment]
Hope I've answered your question, so I'm closing the issue.

**Comment by perqin** [comment]
@divis1969 
When re-init and re-sync I got fetch errors, some outputs are attached below.

```
Fetching projects:  95% (516/543)  Fetching project CyanogenMod/android_frameworks_opt_net_ims
Fetching project CyanogenMod/android_packages_apps_Provision
Fetching project platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8
Fetching project CyanogenMod/android_hardware_intel_img_libdrm
Fetching project platform/external/javassist
Fetching project CyanogenMod/android_packages_apps_AudioFX
Fetching project platform/external/google-fonts/coming-soon
Fetching projects:  96% (522/543)  Fetching project CyanogenMod/android_external_icu
Fetching projects:  99% (538/543)  
error: Exited sync due to fetch errors
```

**Comment by divis1969** [comment]
If you scroll up the sync log, you will find the repository which is failing. The logs also prints the command you can use to fix the issue, something like 'repo sync --force-update <repository>", for example:
`repo sync --force-sync packages/apps/CMUpdater`

Run this command and than run full sync again.

**Comment by perqin** [comment]
@divis1969 Now I have fixed the sync problem but it then failed when syncing working tree. I even install clang but the errors remain.

```
Fetching project CyanogenMod/android_external_icu
Fetching projects: 100% (543/543), done.  
Syncing work tree:  91% (495/543)  error: unable to read sha1 file of bin/clang (f5fc02db43c7b6deae0cccc4b53cde5aa5c59f6c)
error: unable to read sha1 file of bin/clang++ (060d289be84034fca2960b888d3232e7c95b46e2)
error: unable to read sha1 file of bin/clang-tblgen (82b77964606dce0f44c9199b33e33eb6e0c70735)
error: unable to read sha1 file of bin/llvm-as (0cc7fd2dea83136265eef160a6d4dd22d58f6322)
error: unable to read sha1 file of bin/llvm-dis (de1ff3e152d4f6deb5b7bfe84f57ecfcc55b3591)
error: unable to read sha1 file of bin/llvm-link (9ae7c8221118063f47f89d9ab22cb8d04536e916)
error: unable to read sha1 file of bin/tblgen (0d19dd297c8de21ddacbb338da798d1a67eaa644)
error: unable to read sha1 file of lib/clang/3.4/include/Intrin.h (437646471dabf9991892d92c32740a2aa3f860fd)
error: unable to read sha1 file of lib/clang/3.4/include/__wmmintrin_aes.h (2bfa027e07b1b91a789731e65b16aaf561d6d216)
error: unable to read sha1 file of lib/clang/3.4/include/__wmmintrin_pclmul.h (8d1f1b7c0868635510b523f385c5d2d73eea0d3e)
error: unable to read sha1 file of lib/clang/3.4/include/altivec.h (74ce08aa6fea521f01c6698672d180ce6d4c97a5)
error: unable to read sha1 file of lib/clang/3.4/include/ammintrin.h (d87b9cde4405b2a8174b20d73346eabc27859943)
error: unable to read sha1 file of lib/clang/3.4/include/arm_neon.h (c297518e258832e03a68f661a4ba5937f68a79bc)
error: unable to read sha1 file of lib/clang/3.4/include/avx2intrin.h (95744693ac7768eca0a849bc79f56a9fa973db8d)
error: unable to read sha1 file of lib/clang/3.4/include/avxintrin.h (141c4d994bbcf97e35062f6c70382192fb48a72e)
error: unable to read sha1 file of lib/clang/3.4/include/bmi2intrin.h (a05cfad3d027d7f01daad9b503c30d1e10b6bb64)
error: unable to read sha1 file of lib/clang/3.4/include/bmiintrin.h (8cb00f51d3ef5ef88b6fd98ca5ae4b95133bffe0)
error: unable to read sha1 file of lib/clang/3.4/include/cpuid.h (8f12caeb4978081d6ff1d7c1a1f2d23db78aea34)
error: unable to read sha1 file of lib/clang/3.4/include/emmintrin.h (b3f8569524b9833bf02d3938e561d1fd71bfae0f)
error: unable to read sha1 file of lib/clang/3.4/include/f16cintrin.h (f3614c0e3912b76aca30ffadd1eda86b7d5fefab)
error: unable to read sha1 file of lib/clang/3.4/include/float.h (2cb13d3ed5517b13366ed4de93b33c0c266cae96)
error: unable to read sha1 file of lib/clang/3.4/include/fma4intrin.h (c30920df8b03184030c067c65ba895c66cc543d6)
error: unable to read sha1 file of lib/clang/3.4/include/fmaintrin.h (6bfd5a88b3ce8fcd5d16c6c09c13c2d0c39ff0ca)
error: unable to read sha1 file of lib/clang/3.4/include/immintrin.h (15d6e05f979ad84fd6b76b9e3a93b51f8f934fdf)
error: unable to read sha1 file of lib/clang/3.4/include/iso646.h (dca13c5babe5a93f178550bcf0f65401b8f5e3ce)
error: unable to read sha1 file of lib/clang/3.4/include/limits.h (91bd404650e8edcf57aa79a87503cfeee4d01d31)
error: unable to read sha1 file of lib/clang/3.4/include/lzcntintrin.h (62ab5ca2f358061ffd6fb942c22ba8e60d02882c)
error: unable to read sha1 file of lib/clang/3.4/include/mm3dnow.h (5242d99cbd75c268f1a5ec86dc16e7fc7c6c0e93)
error: unable to read sha1 file of lib/clang/3.4/include/mm_malloc.h (305afd31addaa5d2f05f3bb1ddb8911be26d73fd)
error: unable to read sha1 file of lib/clang/3.4/include/mmintrin.h (986870a96883c2a02cb92a18ac73382fa275ac7f)
error: unable to read sha1 file of lib/clang/3.4/include/module.map (9f7944dedbb03dc05995ebaf6bebf890ca90b52e)
error: unable to read sha1 file of lib/clang/3.4/include/nmmintrin.h (f12622d7be68ff95b80193507ccea4a1be1ec544)
error: unable to read sha1 file of lib/clang/3.4/include/pmmintrin.h (6f1fc3294644e7ab26bc0315e430b445cbd72af0)
error: unable to read sha1 file of lib/clang/3.4/include/popcntintrin.h (d439daa8d6a770d9a00aff08895991bed4cd57b6)
error: unable to read sha1 file of lib/clang/3.4/include/prfchwintrin.h (9825bd8c9700f0e9ea08d9cb6cab5e6ed77d55f1)
error: unable to read sha1 file of lib/clang/3.4/include/rdseedintrin.h (0fef1fa496802addd9b8dd4663ba9919366facf4)
error: unable to read sha1 file of lib/clang/3.4/include/rtmintrin.h (26149ca8522dd6cbc41846ad19e5923b1c7ca589)
error: unable to read sha1 file of lib/clang/3.4/include/shaintrin.h (66ed0554b64df9166fff95dc6eec4586a26c9146)
error: unable to read sha1 file of lib/clang/3.4/include/smmintrin.h (53b3ccb4310c70bed2a52258d48a720ba62b2c32)
error: unable to read sha1 file of lib/clang/3.4/include/stdalign.h (3738d1284f95dac0983b39d0cf904358b2dd8e08)
error: unable to read sha1 file of lib/clang/3.4/include/stdarg.h (2957bf058ea8ff35fc275df0857aaaf3a5c85789)
error: unable to read sha1 file of lib/clang/3.4/include/stdbool.h (0467893f3403f10f99fa83e998a313c6ab356b2a)
error: unable to read sha1 file of lib/clang/3.4/include/stddef.h (6a64d6d32a8adf0d936f762423a2e0ec21f07a38)
error: unable to read sha1 file of lib/clang/3.4/include/stdint.h (11529c0c674b39307f3526e97519c30ad832d4f4)
error: unable to read sha1 file of lib/clang/3.4/include/stdnoreturn.h (a7a301d7e0bdb7655f67a0ebfe0f358895b2f55b)
error: unable to read sha1 file of lib/clang/3.4/include/tbmintrin.h (f95e34fbc185c881bd527e3357f4f2f7fb7db641)
error: unable to read sha1 file of lib/clang/3.4/include/tgmath.h (a48e267e60d0c7a659d571d4ad221023a3b67426)
error: unable to read sha1 file of lib/clang/3.4/include/tmmintrin.h (4238f5b389342506394453f3df856e5b4a3963ad)
error: unable to read sha1 file of lib/clang/3.4/include/unwind.h (685c1dfd04e8173df2d91f4b9b4d16b63fe7bade)
error: unable to read sha1 file of lib/clang/3.4/include/varargs.h (b5477d0a6a48aa84058ddb0613ecf7bb59e7d1a3)
error: unable to read sha1 file of lib/clang/3.4/include/wmmintrin.h (369e3c208e537d0fc78a271dff7d89be8b0592a4)
error: unable to read sha1 file of lib/clang/3.4/include/x86intrin.h (399016f11c97bdc3441554a8e90cd604816d55a7)
error: unable to read sha1 file of lib/clang/3.4/include/xmmintrin.h (c68d3ed7b67855e8a2f95d300717112d2ac0bc5b)
error: unable to read sha1 file of lib/clang/3.4/include/xopintrin.h (cc94ca0264c08c35ee61556f6cc3792f25dd99c2)
Traceback (most recent call last):
  File "/home/perqin/Workspaces/AndroidBuilds/CM_M2mini/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/perqin/Workspaces/AndroidBuilds/CM_M2mini/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/perqin/Workspaces/AndroidBuilds/CM_M2mini/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/perqin/Workspaces/AndroidBuilds/CM_M2mini/.repo/repo/subcmds/sync.py", line 769, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/perqin/Workspaces/AndroidBuilds/CM_M2mini/.repo/repo/project.py", line 1247, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/home/perqin/Workspaces/AndroidBuilds/CM_M2mini/.repo/repo/project.py", line 2393, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
```

**Comment by divis1969** [comment]
This looks like the result of some abnormally terminated sync (or some other issue with sync).
You can try to manually remove the following folders:

```
.repo/projects/external/clang.git/
.repo/project-objects/platform/external/clang.git/
external/clang/

```

And run repo sync again.
