### ISSUE TITLE
Падают приложения при попытке выделения текста если применена нестандартная тема оформления.

### ISSUE THREAD

**Issue by agent-007** [divis1969/android_device_meizu_meilan2#45]
Как воспроизвести:
1. Установить тему https://play.google.com/store/apps/details?id=com.oceanlay.theme
2. Применить тему
3. Запустить Google Chrome 
4. Открыть любой сайт и попытаться выделить текст.

Приложение упадёт, бэктрейс ведёт в libminikin, это какая-то библиотека для работы со шрифтами.

**Comment by divis1969** [comment]
Скорее всего что-то в это теме нехорошо с ресурсами
Как будто декодирование битмапа не прокатило
Наверное надо этот APK разбирать и смотреть пристально на res/drawable/ic_menu_search_material.xml

```
04-20 17:36:33.824  7863  7863 D skia    : --- SkImageDecoder::Factory returned null
04-20 17:36:33.852  7863  7863 W System.err: android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_search_material.xml from drawable resource ID #0x1
080401
04-20 17:36:33.853  7863  7863 W System.err:    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2626)
04-20 17:36:33.853  7863  7863 W System.err:    at android.content.res.Resources.loadDrawable(Resources.java:2528)
04-20 17:36:33.853  7863  7863 W System.err:    at android.content.res.Resources.getDrawable(Resources.java:823)
04-20 17:36:33.853  7863  7863 W System.err:    at android.content.res.Resources.getDrawable(Resources.java:799)
04-20 17:36:33.853  7863  7863 W System.err:    at android.content.Context.getDrawable(Context.java:403)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v4.content.a.a(IntentCompatHoneycomb.java:321)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.widget.L.a(TintManager.java:149)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.view.menu.m.getIcon(MenuItemImpl.java:422)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.view.menu.ActionMenuItemView.a(ActionMenuItemView.java:114)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.widget.ActionMenuPresenter.a(ActionMenuPresenter.java:208)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.view.menu.d.a(BaseMenuPresenter.java:182)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.widget.ActionMenuPresenter.a(ActionMenuPresenter.java:194)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.widget.ActionMenuPresenter.b(ActionMenuPresenter.java:453)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.view.menu.i.k(MenuBuilder.java:1138)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.view.menu.d.a(BaseMenuPresenter.java:91)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.widget.ActionMenuPresenter.a(ActionMenuPresenter.java:228)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.view.menu.d.a(BaseMenuPresenter.java:76)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.widget.ActionMenuPresenter.a(ActionMenuPresenter.java:185)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.internal.widget.ActionBarContextView.a(ActionBarContextView.java:184)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.app.AppCompatDelegateImplV7.a(AppCompatDelegateImplV7.java:762)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.app.K.a(AppCompatDelegateImplV14.java:74)
04-20 17:36:33.853  7863  7863 W System.err:    at android.support.v7.app.K.onWindowStartingActionMode(AppCompatDelegateImplV14.java:58)
04-20 17:36:33.853  7863  7863 W System.err:    at org.chromium.base.WindowCallbackWrapper.onWindowStartingActionMode(WindowCallbackWrapper.java:135)
04-20 17:36:33.853  7863  7863 W System.err:    at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2955)
04-20 17:36:33.853  7863  7863 W System.err:    at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2942)
04-20 17:36:33.853  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.853  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.854  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.854  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.854  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.854  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.854  7863  7863 W System.err:    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
04-20 17:36:33.854  7863  7863 W System.err:    at android.view.View.startActionMode(View.java:4890)
04-20 17:36:33.854  7863  7863 W System.err:    at org.chromium.content.browser.ContentViewCore.startDefaultActionMode(ContentViewCore.java:2143)
04-20 17:36:33.854  7863  7863 W System.err:    at org.chromium.content.browser.ContentViewCore.startActionMode(ContentViewCore.java:2139)
04-20 17:36:33.854  7863  7863 W System.err:    at org.chromium.content.browser.ContentViewCore.showSelectActionMode(ContentViewCore.java:2109)
04-20 17:36:33.854  7863  7863 W System.err:    at org.chromium.content.browser.ContentViewCore.onSelectionEvent(ContentViewCore.java:2215)
04-20 17:36:33.854  7863  7863 W System.err:    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-20 17:36:33.854  7863  7863 W System.err:    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
04-20 17:36:33.854  7863  7863 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
04-20 17:36:33.854  7863  7863 W System.err:    at android.os.Looper.loop(Looper.java:135)
04-20 17:36:33.854  7863  7863 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5294)
04-20 17:36:33.854  7863  7863 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-20 17:36:33.854  7863  7863 W System.err:    at java.lang.reflect.Method.invoke(Method.java:372)
04-20 17:36:33.854  7863  7863 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
04-20 17:36:33.854  7863  7863 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
04-20 17:36:33.854  7863  7863 W System.err: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: <bitmap> requires a valid src attribute
04-20 17:36:33.854  7863  7863 W System.err:    at android.graphics.drawable.BitmapDrawable.verifyState(BitmapDrawable.java:731)
04-20 17:36:33.854  7863  7863 W System.err:    at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:719)
04-20 17:36:33.854  7863  7863 W System.err:    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1128)
04-20 17:36:33.855  7863  7863 W System.err:    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1032)
04-20 17:36:33.855  7863  7863 W System.err:    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2616)
04-20 17:36:33.855  7863  7863 W System.err:    ... 45 more

```
